-- SP_HELPTEXT USP_ST_CARGA 

CREATE PROCEDURE [dbo].[USP_ST_CARGA]   
AS  
  
EXEC USP_ST_CARGA_CLIENTE  
EXEC USP_ST_CARGA_EMPRESAS  
EXEC USP_ST_CARGA_PRODUTO  
EXEC USP_ST_CARGA_VENDEDOR  
EXEC USP_ST_CARGA_VENDAS 0  