CREATE VIEW VW_D_CLIENTES

AS
SELECT 
  a.COD_CLIENTE
, a.NOME
, a.NOME_FANTASIA
, ISNULL(DBO.FN_CAMEL_CASE(b.DESCRICAO),'Não Informado') AS CLASSIFICACAO_CLIENTE
, ISNULL(DBO.FN_CAMEL_CASE(c.CIDADE   ) ,'Não Informado') AS CIDADE
, ISNULL(DBO.FN_CAMEL_CASE(d.ESTADO   ) ,'Não Informado') AS ESTADO
, ISNULL(c.UF	     ,'ND') AS UF
FROM ST_CLIENTES					 a
LEFT JOIN ST_CLIENTES_CLASSIFICACOES b ON a.COD_CLASSIFICACAO = b.COD_CLASSIFICACAO
LEFT JOIN ST_CLIENTES_ENDERECO		 c ON a.COD_CLIENTE = c.ENTIDADE
LEFT JOIN ST_CLIENTES_ESTADO		 d ON c.UF = d.UF



--TRATANDO - VW_D_CLIENTES

ALTER VIEW VW_D_CLIENTES
AS
SELECT 0 AS COD_CLIENTE
, 'Não Informado' AS NOME
, 'Não Informado' AS NOME_FANTASIA
, 'Não Informado' AS CLASSIFICACAO_CLIENTE
, 'Não Informado' AS CIDADE
, 'Não Informado' AS ESTADO
, 'ND' AS UF
UNION ALL
SELECT 
  a.COD_CLIENTE
, a.NOME
, a.NOME_FANTASIA
, ISNULL(DBO.FN_CAMEL_CASE(b.DESCRICAO),'Não Informado') AS CLASSIFICACAO_CLIENTE
, ISNULL(DBO.FN_CAMEL_CASE(c.CIDADE   ) ,'Não Informado') AS CIDADE
, ISNULL(DBO.FN_CAMEL_CASE(d.ESTADO   ) ,'Não Informado') AS ESTADO
, ISNULL(c.UF	     ,'ND') AS UF
FROM ST_CLIENTES					 a
LEFT JOIN ST_CLIENTES_CLASSIFICACOES b ON a.COD_CLASSIFICACAO = b.COD_CLASSIFICACAO
LEFT JOIN ST_CLIENTES_ENDERECO		 c ON a.COD_CLIENTE = c.ENTIDADE
LEFT JOIN ST_CLIENTES_ESTADO		 d ON c.UF = d.UF