CREATE VIEW VW_D_EMPRESAS

AS

SELECT COD_EMPRESA
, DBO.FN_CAMEL_CASE (NOME)			AS NOME 
, DBO.FN_CAMEL_CASE (NOME_FANTASIA) AS NOME_FANTASIA  
FROM ST_EMPRESAS


ALTER VIEW VW_D_EMPRESAS
AS
SELECT 0 AS COD_EMPRESA
, 'Não Informado' AS NOME
, 'Não Informado' AS NOME_FANTASIA

UNION ALL
SELECT COD_EMPRESA
, DBO.FN_CAMEL_CASE (NOME)			AS NOME 
, DBO.FN_CAMEL_CASE (NOME_FANTASIA) AS NOME_FANTASIA  
FROM ST_EMPRESAS