CREATE VIEW VW_D_PRODUTOS
AS 
SELECT COD_PRODUTO
      ,dbo.FN_CAMEL_CASE(DESCRICAO			) AS DESCRICAO	 
      ,dbo.FN_CAMEL_CASE(DESCRICAO_REDUZIDA	) AS DESCRICAO_REDUZIDA
      ,ISNULL (dbo.FN_CAMEL_CASE(FAMILIA), 'Não Informada') AS FAMILIA
      ,dbo.FN_CAMEL_CASE(SECAO				) AS SECAO
      ,dbo.FN_CAMEL_CASE(GRUPO				) AS GRUPO
      ,dbo.FN_CAMEL_CASE(SUB_GRUPO			) AS SUB_GRUPO	
      ,dbo.FN_CAMEL_CASE(MARCA				) AS MARCA	
  FROM PBS_PROCFIT_ST.dbo.ST_PRODUTOS
