CREATE VIEW VW_D_PRODUTOS
AS 
SELECT COD_PRODUTO
      ,dbo.FN_CAMEL_CASE(DESCRICAO			) AS DESCRICAO	 
      ,dbo.FN_CAMEL_CASE(DESCRICAO_REDUZIDA	) AS DESCRICAO_REDUZIDA
      ,ISNULL (dbo.FN_CAMEL_CASE(FAMILIA), 'Não Informada') AS FAMILIA
      ,dbo.FN_CAMEL_CASE(SECAO				) AS SECAO
      ,dbo.FN_CAMEL_CASE(GRUPO				) AS GRUPO
      ,dbo.FN_CAMEL_CASE(SUB_GRUPO			) AS SUB_GRUPO	
      ,dbo.FN_CAMEL_CASE(MARCA				) AS MARCA	
  FROM PBS_PROCFIT_ST.dbo.ST_PRODUTOS

--TRATANDO - VW_D_PRODUTOS
ALTER VIEW VW_D_PRODUTOS
AS
SELECT 0 AS COD_PRODUTO 
, 'Não Informado' AS DESCRICAO	 
, 'Não Informado' AS DESCRICAO_REDUZIDA
, 'Não Informado' AS FAMILIA
, 'Não Informado' AS SECAO
, 'Não Informado' AS GRUPO
, 'Não Informado' AS SUB_GRUPO
, 'Não Informado' AS MARCA	
UNION ALL
SELECT COD_PRODUTO
      ,dbo.FN_CAMEL_CASE(DESCRICAO			) AS DESCRICAO	 
      ,dbo.FN_CAMEL_CASE(DESCRICAO_REDUZIDA	) AS DESCRICAO_REDUZIDA
      ,ISNULL (dbo.FN_CAMEL_CASE(FAMILIA), 'Não Informada') AS FAMILIA
      ,dbo.FN_CAMEL_CASE(SECAO				) AS SECAO
      ,dbo.FN_CAMEL_CASE(GRUPO				) AS GRUPO
      ,dbo.FN_CAMEL_CASE(SUB_GRUPO			) AS SUB_GRUPO	
      ,dbo.FN_CAMEL_CASE(MARCA				) AS MARCA	
  FROM PBS_PROCFIT_ST.dbo.ST_PRODUTOS