CREATE VIEW VW_D_VENDEDORES
AS 
SELECT COD_VENDEDOR
	   , DBO.FN_CAMEL_CASE(NOME) AS VENDEDOR
  FROM PBS_PROCFIT_ST.dbo.ST_VENDEDORES

  
--TRATANDO - VW_D_VENDEDORES
ALTER VIEW VW_D_VENDEDORES
AS
SELECT 0 AS COD_VENDEDOR
, 'Não Informado' AS VENDEDOR	 

UNION ALL
SELECT COD_VENDEDOR
	   , DBO.FN_CAMEL_CASE(NOME) AS VENDEDOR
  FROM PBS_PROCFIT_ST.dbo.ST_VENDEDORES