USE PBS_PROCFIT_ST

IF OBJECT_ID('ST_VENDEDORES') IS NULL 
BEGIN 
	CREATE TABLE ST_VENDEDORES (
	COD_VENDEDOR NUMERIC(15)
 ,	NOME		 VARCHAR(100)
)
END

TRUNCATE TABLE ST_VENDEDORES
INSERT INTO ST_VENDEDORES (
COD_VENDEDOR
, NOME	
)
SELECT VENDEDOR
, NOME
FROM PBS_PROCFIT_DADOS.dbo.VENDEDORES
