CREATE PROCEDURE USP_LIMPAR_ST

AS

TRUNCATE TABLE ST_CLIENTES
TRUNCATE TABLE ST_CLIENTES_CLASSIFICACOES
TRUNCATE TABLE ST_CLIENTES_ENDERECOS
TRUNCATE TABLE ST_CLIENTES_ESTADOS
TRUNCATE TABLE ST_EMPRESAS
TRUNCATE TABLE ST_PRODUTOS
TRUNCATE TABLE ST_VENDAS
TRUNCATE TABLE ST_VENDEDORES 
