-- Criando view F_VENDAS
CREATE VIEW VW_F_VENDAS 
AS 
SELECT
 ISNULL(N_DOC		,0) AS N_DOC
,ISNULL(COD_EMPRESA	,0) AS COD_EMPRESA
,ISNULL(COD_CLIENTE	,0) AS COD_CLIENTE
,ISNULL(COD_VENDEDOR,0) AS COD_VENDEDOR
,MOVIMENTO
,ISNULL(COD_PRODUTO,0) AS COD_PRODUTO
,QUANTIDADE
,VENDA_BRUTA
,DESCONTO_TOTAL
,VENDA_LIQUIDA
FROM ST_VENDAS 

DROP VIEW VW_F_VENDAS