-- Criando D_CALENDARIO (p.01)

DECLARE @D_INI DATE = '01/07/2018'
DECLARE @D_FIM DATE = '30/04/2022'

DECLARE @ANO_INI  INT=YEAR(@D_INI)
DECLARE @ANO_FIM  INT=YEAR(@D_FIM)

--SELECT DATEFROMPARTS(@ANO_INI,1,1)
--SELECT DATEFROMPARTS(@ANO_FIM,12,31)

--SELECT DATEDIFF(DAY, DATEFROMPARTS(@ANO_INI,1,1), DATEFROMPARTS(@ANO_FIM,12,31)) + 1
SET @D_INI = DATEFROMPARTS(@ANO_INI,1,1)
SET @D_FIM = DATEFROMPARTS(@ANO_FIM,12,31)

;WITH DATAS AS (
SELECT DATEADD (DAY, a.SEQUENCIA - 1, @D_INI) AS [DATA]
FROM VEZES a
WHERE a.SEQUENCIA <= DATEDIFF(DAY, DATEFROMPARTS(@ANO_INI,1,1), DATEFROMPARTS(@ANO_FIM,12,31)) + 1
)

SELECT [DATA]											 AS [DATA]
	, YEAR ([DATA])										 AS ANO		-- DATEPART(yy,[DATA])
	, DATEFROMPARTS (YEAR([DATA]),1,1)					 AS DATA_INI_ANO
	, DATEFROMPARTS (YEAR([DATA]),12,31)				 AS DATA_FIM_ANO
	, MONTH ([DATA])									 AS MES		-- DATEPART(mm,[DATA])
	, DATEFROMPARTS (YEAR([DATA]), MONTH ([DATA]), 1)	 AS DATA_INI_MES
	, EOMONTH ([DATA])									 AS DATA_FIM_MES
	, DAY(EOMONTH ([DATA]))								 AS DIAS_DO_MES -- DATEPART(dd, EOMONTH ([DATA])) 
	
FROM DATAS










