-- Criando D_CALENDARIO (p.01)

DECLARE @D_INI DATE = '01/07/2018'
DECLARE @D_FIM DATE = '30/04/2022'

DECLARE @ANO_INI  INT=YEAR(@D_INI)
DECLARE @ANO_FIM  INT=YEAR(@D_FIM)

SELECT DATEFROMPARTS(@ANO_INI,1,1)
SELECT DATEFROMPARTS(@ANO_FIM,12,31)

