-- Criando D_CALENDARIO

DECLARE @D_INI DATE = '01/07/2018'
DECLARE @D_FIM DATE = '30/04/2022'

DECLARE @ANO_INI  INT          = YEAR(@D_INI)
DECLARE @ANO_FIM  INT          = YEAR(@D_FIM)
DECLARE @INICIO_ANO_FISCAL INT = 7

--SELECT DATEFROMPARTS(@ANO_INI,1,1)
--SELECT DATEFROMPARTS(@ANO_FIM,12,31)

--SELECT DATEDIFF(DAY, DATEFROMPARTS(@ANO_INI,1,1), DATEFROMPARTS(@ANO_FIM,12,31)) + 1
SET @D_INI = DATEFROMPARTS(@ANO_INI,1,1)
SET @D_FIM = DATEFROMPARTS(@ANO_FIM,12,31)


;WITH DATAS AS (
SELECT DATEADD (DAY, a.SEQUENCIA - 1, @D_INI) AS [DATA]
FROM VEZES a
WHERE a.SEQUENCIA <= DATEDIFF(DAY, DATEFROMPARTS(@ANO_INI,1,1), DATEFROMPARTS(@ANO_FIM,12,31)) + 1
)

SELECT [DATA]											 AS [DATA]
	, YEAR ([DATA])										 AS ANO		-- DATEPART(yy,[DATA])
	, DATEFROMPARTS (YEAR([DATA]),1,1)					 AS DATA_INI_ANO
	, DATEFROMPARTS (YEAR([DATA]),12,31)				 AS DATA_FIM_ANO
	, MONTH ([DATA])									 AS MES		-- DATEPART(mm,[DATA])
	, DATEFROMPARTS (YEAR([DATA]), MONTH ([DATA]), 1)	 AS DATA_INI_MES
	, EOMONTH ([DATA])									 AS DATA_FIM_MES
	, DAY(EOMONTH ([DATA]))								 AS DIAS_DO_MES -- DATEPART(dd, EOMONTH ([DATA])) 
	, CONCAT(
			YEAR([DATA]),
			 CONCAT(
			  REPLICATE('0', 2 -LEN ( MONTH([DATA]))),
			   MONTH([DATA]) ))							AS ANO_MES 
	, DAY([DATA])										AS DIA -- DATEPART(dd, EOMONTH ([DATA])) 
	, DATENAME(dw,[DATA])								AS NOME_DIA_SEMANA
	, LEFT(DATENAME(dw,[DATA]) , 3)						AS NOME_DIA_SEMANA_SHORT
	, DATEPART( [WEEKDAY] ,[DATA])						AS DIA_SEMANA
	, DATEPART( DY,[DATA])								AS DIA_DO_ANO
	, DATENAME(MM ,[DATA])								AS NOME_MES
	, LEFT(DATENAME(MM ,[DATA]) ,3)						AS NOME_MES_SHORT
	, DATEPART (QQ, [DATA])								AS TRIMESTRE 
	, CONCAT ('Tr', DATEPART(QQ, [DATA]))				AS NOME_TRIMESTRE
	, DATEPART(WK,[DATA])								AS SEMANA_DO_ANO
	, CASE @INICIO_ANO_FISCAL
			WHEN 1 THEN YEAR ([DATA])
			ELSE YEAR([DATA]) + CAST (( MONTH([DATA]) + (13 - @INICIO_ANO_FISCAL)) /13 AS INT)
			END

FROM DATAS
