USE PBS_PROCFIT_ST 

IF OBJECT_ID('ST_PRODUTOS') IS NULL 
BEGIN 
	CREATE TABLE ST_PRODUTOS( COD_PRODUTO NUMERIC(15)
,	  DESCRICAO	   VARCHAR(100)
,	  DESCRICAO_REDUZIDA VARCHAR(60)
,     FAMILIA     VARCHAR(80)
,	  SECAO       VARCHAR(80)
,     GRUPO    	  VARCHAR(80)
,	  SUB_GRUPO   VARCHAR(80)
,	  MARCA  	  VARCHAR(80)
	)
 END

 TRUNCATE TABLE ST_PRODUTOS

INSERT INTO ST_PRODUTOS (
 COD_PRODUTO
, DESCRICAO
, DESCRICAO_REDUZIDA
, FAMILIA
, SECAO
, GRUPO
, SUB_GRUPO
, MARCA
)

SELECT a.PRODUTO
,	   a.DESCRICAO
,	   a.DESCRICAO_REDUZIDA
,      b.DESCRICAO AS FAMILIA
,	   c.DESCRICAO AS SECAO
,      d.DESCRICAO AS GRUPO
,	   e.DESCRICAO AS SUB_GRUPO
,	   f.DESCRICAO AS MARCA
FROM PBS_PROCFIT_DADOS.dbo.PRODUTOS				    a
LEFT JOIN  PBS_PROCFIT_DADOS.dbo.FAMILIAS_PRODUTOS  b ON a.FAMILIA_PRODUTO  = b.FAMILIA_PRODUTO
	 JOIN  PBS_PROCFIT_DADOS.dbo.SECOES_PRODUTOS	c ON a.SECAO_PRODUTO	 = c.SECAO_PRODUTO
	 JOIN  PBS_PROCFIT_DADOS.dbo.GRUPOS_PRODUTOS    d ON a.GRUPO_PRODUTO	 = d.GRUPO_PRODUTO
	 JOIN  PBS_PROCFIT_DADOS.dbo.SUBGRUPOS_PRODUTOS e ON a.SUBGRUPO_PRODUTO = e.SUBGRUPO_PRODUTO
LEFT JOIN  PBS_PROCFIT_DADOS.dbo.MARCAS			    f ON a.MARCA			 = f.MARCA


