CREATE PROCEDURE USP_ST_CARGA_CLIENTE
AS

--------------------------------
-- VERIFICAR SE O SCHEMA EXISTE 
---------------------------------

--USE PBS_PROCFIT_ST
IF OBJECT_ID('ST_CLIENTES') IS NULL
BEGIN 
CREATE TABLE ST_CLIENTES(
  COD_CLIENTE		NUMERIC(15)
, NOME				VARCHAR(100)
, NOME_FANTASIA		VARCHAR(60)
, COD_CLASSIFICACAO NUMERIC(15)
)
END

IF OBJECT_ID('ST_CLIENTES_CLASSIFICACOES') IS NULL
BEGIN 
CREATE TABLE ST_CLIENTES_CLASSIFICACOES(
  COD_CLASSIFICACAO NUMERIC(15)
, DESCRICAO VARCHAR(50)
)
END

IF OBJECT_ID('ST_CLIENTES_ENDERECO') IS NULL
BEGIN 
CREATE TABLE ST_CLIENTES_ENDERECO(
 ENTIDADE NUMERIC(15)
, CIDADE  VARCHAR(100)
, UF	  CHAR(2)
)
END

IF OBJECT_ID('ST_CLIENTES_ESTADO') IS NULL
BEGIN 
CREATE TABLE ST_CLIENTES_ESTADO(
 UF	  CHAR(2)
, ESTADO VARCHAR(100)
)
END

--LIMPA STAGE AREA 
---------------------

TRUNCATE TABLE ST_CLIENTES
TRUNCATE TABLE ST_CLIENTES_CLASSIFICACOES
TRUNCATE TABLE ST_CLIENTES_ENDERECO
TRUNCATE TABLE ST_CLIENTES_ESTADO

--- POPULA STAGE AREA 


INSERT INTO ST_CLIENTES(
  COD_CLIENTE		
, NOME				
, NOME_FANTASIA		
, COD_CLASSIFICACAO 
)
SELECT ENTIDADE
, NOME
, NOME_FANTASIA
, CLASSIFICACAO_CLIENTE
FROM PBS_PROCFIT_DADOS.dbo.ENTIDADES 
--------------------------------------------------
INSERT INTO ST_CLIENTES_CLASSIFICACOES(
COD_CLASSIFICACAO
, DESCRICAO
)
SELECT CLASSIFICACAO_CLIENTE
, DESCRICAO
FROM PBS_PROCFIT_DADOS.dbo.CLASSIFICACOES_CLIENTES
-------------------------------------------------------
INSERT INTO ST_CLIENTES_ENDERECO(
ENTIDADE
, CIDADE
, UF	
)
SELECT ENTIDADE
,	   CIDADE
,	   ESTADO
FROM PBS_PROCFIT_DADOS.dbo.ENDERECOS
---------------------------------------------------
INSERT INTO ST_CLIENTES_ESTADO(
 UF	
, ESTADO 
)
SELECT ESTADO
,	   NOME
FROM PBS_PROCFIT_DADOS.dbo.ESTADOS

-- ABRE NOVA CONSULTA 
EXEC USP_ST_CARGA_CLIENTE