-- Criando e populando a ST_CLIENTES 
/* TABELA DE ENTIDADE NO ST 
ENTIDADE
NOME
NOME_FANTASIA
CLASSIFICACAO_CLIENTE
*/
use PBS_PROCFIT_ST
CREATE TABLE ST_CLIENTES(
  COD_CLIENTE		NUMERIC(15)
, NOME				VARCHAR(100)
, NOME_FANTASIA		VARCHAR(60)
, COD_CLASSIFICACAO NUMERIC(15)
)

TRUNCATE TABLE ST_CLIENTES

INSERT INTO ST_CLIENTES(
  COD_CLIENTE		
, NOME				
, NOME_FANTASIA		
, COD_CLASSIFICACAO 
)
SELECT a.ENTIDADE
, a.NOME
, a.NOME_FANTASIA
, a.CLASSIFICACAO_CLIENTE
FROM PBS_PROCFIT_DADOS.dbo.ENTIDADES a	-- OU FROM PBS_PROCFIT_DADOS..ENTIDADES	a

SELECT * FROM ST_CLIENTES

-- VEREFICAR SE ELA EXISTE 
SELECT OBJECT_ID ('ST_CLIENTES') -- SE ESTIVER JA NA BASE PBS_PROCFIT_ST

IF OBJECT_ID('ST_CLIENTES') IS NULL
BEGIN 
	CREATE TABLE ST_CLIENTES(
	  COD_CLIENTE		NUMERIC(15)
	, NOME				VARCHAR(100)
	, NOME_FANTASIA		VARCHAR(60)
	, COD_CLASSIFICACAO NUMERIC(15)
	)
END