-- Criando e preenchendo ST_CLIENTES_CLASSIFICACOES
/* TABELA DE CLASSIFICACAO_CLIENTES NO ST
CLASSIFICACAO_CLIENTE
DESCRICAO
*/

IF OBJECT_ID('ST_CLIENTES_CLASSIFICACOES') IS NULL
BEGIN 
CREATE TABLE ST_CLIENTES_CLASSIFICACOES(
  COD_CLASSIFICACAO NUMERIC(15)
, DESCRICAO VARCHAR(50)
)
END

TRUNCATE TABLE ST_CLIENTES_CLASSIFICACOES
INSERT INTO ST_CLIENTES_CLASSIFICACOES(
COD_CLASSIFICACAO
, DESCRICAO
)
SELECT CLASSIFICACAO_CLIENTE
, DESCRICAO
FROM PBS_PROCFIT_DADOS.dbo.CLASSIFICACOES_CLIENTES

SELECT * FROM ST_CLIENTES_CLASSIFICACOES