use PBS_PROCFIT_DADOS
-- MODULO 06 --
-- UNION ALL - JUNTA O RESULTADO DE DUAS CONSULTAS
-- UNION     - JUNTA O RESULTADO DISTINTO DE DUAS CONSULTAS
-- EXCEPT - QUANDO SE QUER QUE APAREÇAM OS REGISTROS DA CONSULTA A QUE NÃO SÃO IGUAIS AOS DA CONSULTA B
-- INTERSECT - INTERSEÇÃO ENTRE DUAS CONSULTAS 
/* 
1. TODAS AS CONSULTAS DEVEM TER O MESMOS NUMEROS DE COLUNAS
2. TODOS OS TIPOS DE DADOS DEVEM SER COMPATIVEIS ENTRE AS COLUNAS 
3. OS ALIAS DAS COLUNAS FICAM NO PRIMEIRO COMANDO SELECT
4. SEMPRE O ORDER BY FICA NO ULTIMO COMANDO SELECT
*//*
SELECT 'PF'			AS TIPO_CLIENTE
, ENTIDADE			AS COD_CLIENTE
, NOME				AS NOME_CLIENTE
, INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL
, DATA_CADASTRO
FROM PESSOAS_FISICAS

UNION ALL

SELECT 'PJ'
, ENTIDADE
, NOME
, INSCRICAO_FEDERAL
, NULL
FROM PESSOAS_JURIDICAS

UNION ALL 

SELECT'EN'
, ENTIDADE
, NOME
, INSCRICAO_FEDERAL
, NULL
FROM ENTIDADES
ORDER BY COD_CLIENTE
*/
-- 1 FORMA 
SELECT 'CONTAS A RECEBER' as TIPOS, B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL, SUM(A.VALOR) AS VALOR_RECEBER , 0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL 

SELECT'CONTAS A PAGAR' AS TIPOS, B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL, 0.00 AS VALOR_RECEBER, SUM(A.VALOR) AS VALOR_PAGAR
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL
ORDER BY ENTIDADE

-- 2. FORMA
SELECT B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL, SUM(A.VALOR) AS VALOR_RECEBER , 0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL 

SELECT B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL, 0.00 AS VALOR_RECEBER, SUM(A.VALOR) AS VALOR_PAGAR
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL
ORDER BY ENTIDADE

-- UNION     - JUNTA O RESULTADO DISTINTO DE DUAS CONSULTAS

SELECT ENTIDADE		AS COD_CLIENTE
, NOME				AS NOME_CLIENTE
, INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL
, DATA_CADASTRO
FROM PESSOAS_FISICAS

UNION 

SELECT  ENTIDADE
, NOME
, INSCRICAO_FEDERAL
, NULL
FROM PESSOAS_JURIDICAS

UNION 

SELECT ENTIDADE
, NOME
, INSCRICAO_FEDERAL
, NULL
FROM ENTIDADES
ORDER BY COD_CLIENTE

-- EXCEPT - QUANDO SE QUER QUE APAREÇAM OS REGISTROS DA CONSULTA A QUE NÃO SÃO IGUAIS AOS DA CONSULTA B

SELECT B.ENTIDADE
, B.NOME
, B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL 

EXCEPT

SELECT B.ENTIDADE
, B.NOME
, B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL 
ORDER BY ENTIDADE

-- INTERSECT - INTERSEÇÃO ENTRE DUAS CONSULTAS 

SELECT B.ENTIDADE
, B.NOME
, B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL 

INTERSECT 

SELECT B.ENTIDADE
, B.NOME
, B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL 

ORDER BY ENTIDADE