USE PBS_PROCFIT_DADOS
-- MODULO 8 --
-- Entendendo a diferença entre temporárias locais e temporárias globais
-- TABELAS TEMPORARIAS (#)- São visíveis apenas para a sessão de conexão em que foram criadas, o que significa que outros usuários ou sessões de conexão não podem acessá-las. Além disso, elas são descartadas automaticamente quando a sessão é encerrada.
-- TABELAS TEMPORARIAS GLOBAIS (##) - São visíveis para todas as sessões de conexão no banco de dados, o que significa que outras sessões de usuários podem acessá-las. Além disso, elas persistem mesmo após a desconexão do usuário que as criou e existem até que sejam explicitamente descartadas ou até que a conexão com o banco de dados seja encerrada.

--> CRIANDO UMA TABELA TEMPORARIA 
CREATE TABLE #TBLTEMPORARIA
(
  COD_CLIENTE INT
, NOME_CLIENTE VARCHAR(80)
, TOTAL_VENDIDO MONEY
)
SELECT * FROM #TBLTEMPORARIA

--> CRIANDO UMA TABELA TEMPORARIA GLOBAL 
CREATE TABLE ##TBLTEMPORARIA
(
  COD_CLIENTE INT
, NOME_CLIENTE VARCHAR(80)
, TOTAL_VENDIDO MONEY
)
SELECT * FROM ##TBLTEMPORARIA

SELECT B.ENTIDADE		as entidade
, B.NOME				as nome_cliente
, SUM(A.VENDA_LIQUIDA)	as total_vendido
 INTO #TBLclientesVenda
FROM VENDAS_ANALITICAS A
JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME

select*from #TBLclientesVenda

SELECT B.ENTIDADE		as entidade
, B.NOME				as nome_cliente
, SUM(A.VENDA_LIQUIDA)	as total_vendido
 INTO ##TBLclientesVendag
FROM VENDAS_ANALITICAS A
JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME

select*from ##TBLclientesVendag


-- RECUPERAR O TOTAL A PAGAR E O VALOR PAGO POR ANO E MES DE CADA ENTIDADE 
-- RECUPERAR O TOTAL A RECEBER E O VALOR RECEBIDO POR ANO E MES DE CADA ENTIDADE
-- RECUPERAR TODAS AS VENDAS POR ANO E MES DE CADA ENTIDADE 

-- TOTAL A PAGAR PARA CLIENTE 
SELECT A.ENTIDADE			AS CLIENTE
,	   YEAR(A.MOVIMENTO)	AS ANO
,	   MONTH(A.MOVIMENTO)	AS MES
, CASE WHEN SUM(A.VALOR) < SUM(B.SALDO)
	   THEN SUM(B.SALDO)
	   ELSE SUM(A.VALOR)
  END AS TOTAL_PAGAR
,	   SUM(B.SALDO)  AS SALDO_DEVEDOR
,CASE WHEN SUM(A.VALOR) < SUM(B.SALDO)
	   THEN SUM(B.SALDO)
	   ELSE SUM(A.VALOR) end - SUM(B.SALDO) AS TOTAL_PAGO
into #total_pagar_cliente
FROM TITULOS_PAGAR A
JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY A.ENTIDADE, YEAR(A.MOVIMENTO)  , MONTH(A.MOVIMENTO)
ORDER BY ANO

-- TOTAL A RECEBIDO DO CLIENTE 

SELECT A.ENTIDADE AS CLIENTE
,	   YEAR(A.MOVIMENTO) AS ANO
,	   MONTH(A.MOVIMENTO) AS MES
,	   SUM(A.VALOR) AS TOTAL_RECEBER
,	   SUM(B.SALDO)  AS SALDO_RECEBER
,	   SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_RECEBIDO
into #total_cliente_receber
FROM TITULOS_RECEBER A 
JOIN TITULOS_RECEBER_SALDO B ON A.TITULO_RECEBER = B.TITULO_RECEBER
GROUP BY A.ENTIDADE, YEAR(A.MOVIMENTO)  , MONTH(A.MOVIMENTO)
ORDER BY ANO
DELETE #total_cliente_receber
-- TOTAL VENDIDO POR CLIENTE 

SELECT A.CLIENTE		 AS CLIENTE
,	   YEAR(A.MOVIMENTO) AS ANO
,	   MONTH(A.MOVIMENTO) AS MES
,	   SUM(A.VENDA_LIQUIDA) AS TOTAL_VENDIDO
into #tbltotal_vendido_cliente
FROM VENDAS_ANALITICAS A
GROUP BY A.CLIENTE, YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

-- RESULTADO FINAL POR CLIENTE 
SELECT A.*
, B.TOTAL_RECEBER
, B.SALDO_RECEBIDO
, C.TOTAL_PAGAR
, C.SALDO_DEVEDOR
FROM #tbltotal_vendido_cliente A
JOIN #total_cliente_receber B ON A.CLIENTE = B.CLIENTE 
							AND A.ANO = B.ANO 
							AND A.MES = B.MES
JOIN #total_pagar_cliente C ON A.CLIENTE = C.CLIENTE
							AND A.ANO = C.ANO
							AND A.MES = C.MES

