USE PBS_PROCFIT_DADOS
 SELECT * FROM EMPRESAS_USUARIAS
 SP_HELP EMPRESAS_USUARIAS 

SELECT EMPRESA_USUARIA AS EMPRESA
,NOME AS NOME_EMPRESA
FROM EMPRESAS_USUARIAS 

--DESAFIO--
/* TABELA: ENTIDADES
 ENTIDADE = CODIGO DO CLIENTE -> COD_CLIENTE 
 NOME= NOME DO CLIENTE -> NOME 
 INSCRIÇÃO FEDERAL - CPF OU CNPJ -> CPF_CNPJ
 ATIVO = CLENTE ATIVO OU NÃO -> CADASTRO_ATIVO  */  

SELECT * FROM ENTIDADES

SELECT ENTIDADE    AS COD_CLIENTE
 ,NOME              AS NOME
 ,INSCRICAO_FEDERAL AS CPF_CNPJ
 ,ATIVO             AS CADASTRO_ATIVO
	FROM ENTIDADES
 
 /*
 + = ADIÇÃO
 - = SUBTRAÇÃO 
 * = MULTIPLICAÇÃO 
 / = DIVISÃO 
 % = RESTO 
 */

 SELECT 10 + 5 AS ADICAO
 SELECT 10 - 5 AS SUBTRACAO
 SELECT 10 * 5 AS MULTIPLICACAO
 SELECT 10 / 5 AS DIVISAO
 SELECT 10.00 / 4.00 AS DIVISAO_2
 SELECT 10 % 5 AS RESTO
 SELECT 10 % 4 AS RESTO_2

 SELECT PRODUTO
, QUANTIDADE
, VENDA_BRUTA / QUANTIDADE AS VALOR_UNITARIO 
, VENDA_BRUTA
, VENDA_BRUTA / QUANTIDADE * QUANTIDADE  AS VALOR_UNITARIO1
FROM VENDAS_ANALITICAS

SELECT VENDA_BRUTA
,ICMS_ALIQUOTA
,VENDA_BRUTA - (VENDA_BRUTA * ICMS_ALIQUOTA /100) AS LUCRO_LIQUIDO 
,VENDA_BRUTA * ICMS_ALIQUOTA /100                 AS IMPOSTO 
FROM VENDAS_ANALITICAS
WHERE VENDA_ANALITICA = 18035

--DESAFIO--

SELECT PRODUTO
, QUANTIDADE
, VALOR_UNITARIO
, VALOR_UNITARIO * QUANTIDADE                      AS VALOR_TOTAL_PRODUTO
, ICMS_ALIQUOTA
, VALOR_UNITARIO * QUANTIDADE * ICMS_ALIQUOTA /100 AS ICMS_VALOR
FROM NF_FATURAMENTO_PRODUTOS

/*
 OPERADORES DE CONCATENAÇÃO 
1. FORMA -> + ( OPERADOR ARITIMETICO DE SOMA OU OPERADOR DE CONCATENAÇÃO)
 REGRA GERAL : OLHAS OS TIPOS DE DADOS
1. PASSA PELO MENOS UM VALOR NÚMERO 

SELECT 5 + 2 (VAI SOMAR)
SELECT 5 + 'T' ( DA MENSAGEM DE ERRO POR QUE NÃO CONSEGUE CONVERTER T EM NUMERO)
SELECT 5 + '2' (CONSEGUE CONVERTER 2 EM NUMERO)

2.CASO NÃO EXISTA NENHUM DADO NUMÉRICO 

SELECT 'JOÃO' + ' DA SILVA' (JOÃO DA SILVA)
SELECT '5' + '2' (52)
*/

--PRÁTICA

SELECT VENDA_LIQUIDA + DESCONTO FROM VENDAS_ANALITICAS

SELECT OPERACAO_FISCAL + SITUACAO_TRIBUTARIA FROM VENDAS_ANALITICAS

SELECT ENDERECO
, CIDADE
, ESTADO
, CIDADE + '_' + ESTADO
FROM ENDERECOS

/* 2. FORMA É ULTILIZAR A FUNÇÃO NATIVA CONCAT
SELECT CONCAT (5,2)  (52)
SELECT CONCAT(5,'T') (5T) 
SELECT CONCAT (5,'2') (52) 
SELECT CONCAT('JOÃO',' DA SILVA') (JOÃO DA SILVA)
SELECT CONCAT ('5','2') 
*/
SELECT ENDERECO
, CIDADE
, ESTADO
, CIDADE + '_' + ESTADO AS OPERADOR_MAIS
, CONCAT (CIDADE , '_' , ESTADO) AS OPERADOR_CONCAT
, CONCAT (CIDADE , ESTADO) 
FROM ENDERECOS

--DESAFIO--

SELECT ENTIDADE
, NOME_FANTASIA
, CONCAT (ENTIDADE,'_', NOME_FANTASIA) AS CLIENTES
FROM ENTIDADES

SELECT DESCRICAO
, UNIDADE_MEDIDA
, CONCAT (DESCRICAO,'_',UNIDADE_MEDIDA)
, DESCRICAO + '_' + UNIDADE_MEDIDA AS PRODUTO
FROM PRODUTOS 

select produto 
, movimento 
, quantidade
, venda_bruta
from VENDAS_ANALITICAS 
order by produto asc, venda_bruta desc

-- crescente -> ASC
-- decrescente -> DESC

--DESAFIO--

select entidade as C0D_CLIENTE
, INSCRICAO_FEDERAL
, Concat(INSCRICAO_FEDERAL, '_', NOME) as CLIENTE
, DATA_CADASTRO
from ENTIDADES
ORDER BY DATA_CADASTRO DESC

/*
 OPERADORES DE COMPARAÇÃO 
= IGUAL A 
<> DIFERENTE DE
!= DIFERENTE DE 
> MAIOR QUE 
>= MAIOR OU IGUAL A 
< MENOR QUE 
<= MENOR OU IGUAL A 
*/

SELECT * FROM ENTIDADES
WHERE ENTIDADE <= 1001
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ENTIDADE <> 1
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ENTIDADE < 3100
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ATIVO = 'N'
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ATIVO <> 'S'
ORDER BY ENTIDADE 


--DESAFIO 1--

SELECT CONCAT (ESPECIE_FISCAL,'_', DOCUMENTO_NUMERO) AS DOCUMENTO
, VENDEDOR
, MOVIMENTO
, VENDA_BRUTA
,QUANTIDADE
, PRODUTO
, VENDA_BRUTA / QUANTIDADE  AS VALOR_UNITARIO 
FROM VENDAS_ANALITICAS
WHERE MOVIMENTO > '01/06/2020'
ORDER BY MOVIMENTO ASC


--DESAFIO 2--

SELECT VENDEDOR
, MOVIMENTO
, PRODUTO
, QUANTIDADE
, VENDA_BRUTA
, CONCAT (ESPECIE_FISCAL,'_', DOCUMENTO_NUMERO) AS DOCUMENTO
, VENDA_BRUTA / QUANTIDADE  AS VALOR_UNITARIO 
FROM VENDAS_ANALITICAS
WHERE PRODUTO = '34912'
ORDER BY MOVIMENTO DESC

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE = 'SAO PAULO'


--LIKE -> OPERADO DE FILTRO DE CAMPOS VARCHAR (TEXTO)
--(%) -> INDEPENDENTE DO QUE VENHA 
--(_) -> SUBSTITUICAO 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'SAO PAULO' -- CORREPONDENCIA EXATA 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE '%LO' -- O QUE TERMINA COM TEXTO INFORMADO(%TEXTO)

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'SA%' -- O QUE COMEÇA COM TEXTO INFOMADO (TEXTO%)

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE '%SA%' -- O QUE CONTÉM COM TEXTO INFOMADO (%TEXTO%)

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'FO_TALEZA' 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'SA_V%' 

SELECT NOME FROM ENTIDADES
WHERE NOME LIKE 'CLIENT__112%'

SELECT NOME FROM ENTIDADES
WHERE NOME LIKE 'CL_ENT__1120'


--NOT LIKE(<>)
--(%) -> INDEPENDENTE DO QUE VENHA 
--(_) -> SUBSTITUICAO 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE NOT LIKE 'SA%'

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE NOT LIKE '%ES'


--DESAFIO 01--

SELECT CIDADE
,ESTADO
FROM ENDERECOS
WHERE CIDADE LIKE 'S_O%'
ORDER BY CIDADE DESC

--DESAFIO 02--

SELECT NOME
,DATA_CADASTRO
FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'


-- AND (E) -> TODAS AS CONDIÇÕES DEVERÃO SER OBEDECIDAS 
-- OR (OU) -> SE PELO MENOS UMA DAS CONDIÇÕES FOREM OBEDECIDAS 

SELECT * FROM ENTIDADES
WHERE ATIVO = 'S'
 AND DATA_CADASTRO >= '18/06/2019'
 AND INSCRICAO_FEDERAL NOT LIKE '%0001%'
 
 SELECT * FROM ENTIDADES
WHERE ATIVO = 'N'
 OR DATA_CADASTRO >= '18/06/2019'
 OR INSCRICAO_FEDERAL NOT LIKE '%0001%'

 SELECT * FROM ENTIDADES
WHERE ENTIDADE = 1001
   OR ENTIDADE = 1002
   OR ENTIDADE = 1003

-- IN  
-- NOT IN 

SELECT * FROM ENTIDADES
WHERE ENTIDADE IN (1001,1,1035,1258,1455,1254)

SELECT CIDADE, ESTADO FROM ENDERECOS
WHERE ESTADO IN ('CE','SP','BA','RJ')
ORDER BY ESTADO 

SELECT * FROM ENTIDADES
WHERE ENTIDADE NOT IN (1001,1,1035,1258,1455,1254)

SELECT CIDADE, ESTADO FROM ENDERECOS
WHERE ESTADO NOT IN ('CE','SP','BA','RJ')
ORDER BY ESTADO 

--DESAFIO 01--

SELECT CLIENTE
, QUANTIDADE
, VENDEDOR
, PRODUTO
, MOVIMENTO
FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876, 1422, 2249)
AND QUANTIDADE > 0
AND VENDEDOR IN (4,16)
AND PRODUTO IN( 34726, 34304, 34394, 34593)
ORDER BY MOVIMENTO

--DESAVIO 02--

SELECT CLIENTE
, QUANTIDADE
, VENDEDOR
, PRODUTO
, MOVIMENTO
FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876, 1422, 2249)
AND QUANTIDADE > 0
AND VENDEDOR IN (4,16)
AND PRODUTO NOT IN( 34726, 34304, 34394, 34593)
ORDER BY MOVIMENTO
 

-- BETWEEN -> ENTRE 

SELECT * FROM ENTIDADES
WHERE ENTIDADE BETWEEN 1001 AND 1010

SELECT * FROM TITULOS_RECEBER
WHERE VALOR  BETWEEN 0.00 AND 100.00
ORDER BY VALOR 

SELECT * FROM ENTIDADES
WHERE DATA_CADASTRO BETWEEN '01/01/2018' AND '31/01/2018'
ORDER BY DATA_CADASTRO

--DESAFIO 01--

SELECT MOVIMENTO
, ENTIDADE
, TITULO
, VALOR
FROM TITULOS_RECEBER
where MOVIMENTO >= '01/01/2020' 
AND ENTIDADE IN (1874, 2308, 1520)
AND TITULO LIKE '%/1%'
AND (VALOR BETWEEN 150.00 AND 255.23
	   OR VALOR BETWEEN 425.57 AND 550.12)
ORDER BY VALOR ASC

select top 100 
* from VENDAS_ANALITICAS

select top 100 
  cliente 
, produto
, quantidade
, venda_bruta
from VENDAS_ANALITICAS

select top 5 percent
  cliente 
, produto
, quantidade
, venda_bruta
, movimento
from VENDAS_ANALITICAS
where movimento >= '01/01/2020'
order by quantidade asc

-- distinct -> ultilizado para deixar valores unicos (não repetidos)

select distinct 
cidade
, estado
from ENDERECOS
where estado = 'sp'
order by cidade 

select distinct 
 cliente
 , produto 
 , venda_liquida + desconto as venda_final 
 from VENDAS_ANALITICAS

