use PBS_PROCFIT_ST

SELECT 
  a.COD_CLIENTE
, a.NOME
, a.NOME_FANTASIA
, ISNULL( b.DESCRICAO, 'NÃO INFORMADO') AS CLASSIFICACAO_CLIENTE
, ISNULL(c.CIDADE,'NÃO INFORMADO') AS CIDADE
, ISNULL(d.ESTADO,'NÃO INFORMADO') AS ESTADO
, ISNULL(c.UF	 ,'ND') AS UF
FROM ST_CLIENTES					 a
LEFT JOIN ST_CLIENTES_CLASSIFICACOES b ON a.COD_CLASSIFICACAO = b.COD_CLASSIFICACAO
LEFT JOIN ST_CLIENTES_ENDERECO		 c ON a.COD_CLIENTE = c.ENTIDADE
LEFT JOIN ST_CLIENTES_ESTADO		 d ON c.UF = d.UF