---- Criando e preenchendo ST_CLIENTES_ESTADO
/* TABELA DE ESTADOS NO ST
UF
ESTADO (DESCRIÇÃO DA UF)
*/

USE PBS_PROCFIT_ST
IF OBJECT_ID('ST_CLIENTES_ESTADO') IS NULL
BEGIN 
CREATE TABLE ST_CLIENTES_ESTADO(
 UF	  CHAR(2)
, ESTADO VARCHAR(100)
)
END

TRUNCATE TABLE ST_CLIENTES_ESTADO
INSERT INTO ST_CLIENTES_ESTADO(
 UF	
, ESTADO 
)
SELECT ESTADO
,	   NOME
FROM PBS_PROCFIT_DADOS.dbo.ESTADOS

SELECT * FROM ST_CLIENTES_ESTADO