--USE PBS_PROCFIT_DADOS
--SELECT * FROM EMPRESAS_USUARIAS
--SP_HELP EMPRESAS_USUARIAS 

/* SELECT EMPRESA_USUARIA AS EMPRESA
,NOME AS NOME_EMPRESA
FROM EMPRESAS_USUARIAS */

------------
--DESAFIO--
------------

 /* TABELA: ENTIDADES
 ENTIDADE = CODIGO DO CLIENTE -> COD_CLIENTE 
 NOME= NOME DO CLIENTE -> NOME 
 INSCRIÇÃO FEDERAL - CPF OU CNPJ -> CPF_CNPJ
 ATIVO = CLENTE ATIVO OU NÃO -> CADASTRO_ATIVO  */  

 --SELECT * FROM ENTIDADES

 /* 
 SELECT ENTIDADE    AS COD_CLIENTE
 ,NOME              AS NOME
 ,INSCRICAO_FEDERAL AS CPF_CNPJ
 ,ATIVO             AS CADASTRO_ATIVO
 FROM ENTIDADES
 */

 /*
 + = ADIÇÃO
 - = SUBTRAÇÃO 
 * = MULTIPLICAÇÃO 
 / = DIVISÃO 
 % = RESTO 
 */

 /*
 SELECT 10 + 5 AS ADICAO
 SELECT 10 - 5 AS SUBTRACAO
 SELECT 10 * 5 AS MULTIPLICACAO
 SELECT 10 / 5 AS DIVISAO
 SELECT 10.00 / 4.00 AS DIVISAO_2
 SELECT 10 % 5 AS RESTO
 SELECT 10 % 4 AS RESTO_2
 */


 /*
 SELECT PRODUTO
, QUANTIDADE
, VENDA_BRUTA / QUANTIDADE AS VALOR_UNITARIO 
, VENDA_BRUTA
, VENDA_BRUTA / QUANTIDADE * QUANTIDADE  AS VALOR_UNITARIO1
FROM VENDAS_ANALITICAS
*/

/*
SELECT VENDA_BRUTA
,ICMS_ALIQUOTA
,VENDA_BRUTA - (VENDA_BRUTA * ICMS_ALIQUOTA /100) AS LUCRO_LIQUIDO 
,VENDA_BRUTA * ICMS_ALIQUOTA /100                 AS IMPOSTO 
FROM VENDAS_ANALITICAS
WHERE VENDA_ANALITICA = 18035
*/

------------
--DESAFIO--
------------
/*
SELECT PRODUTO
, QUANTIDADE
, VALOR_UNITARIO
, VALOR_UNITARIO * QUANTIDADE                      AS VALOR_TOTAL_PRODUTO
, ICMS_ALIQUOTA
, VALOR_UNITARIO * QUANTIDADE * ICMS_ALIQUOTA /100 AS ICMS_VALOR
FROM NF_FATURAMENTO_PRODUTOS
*/

/*
--- OPERADORES DE CONCATENAÇÃO 
-- 1. FORMA -> + ( OPERADOR ARITIMETICO DE SOMA OU OPERADOR DE CONCATENAÇÃO)
 REGRA GERAL : OLHAS OS TIPOS DE DADOS
1. PASSA PELO MENOS UM VALOR NÚMERO 

SELECT 5 + 2 (VAI SOMAR)
SELECT 5 + 'T' ( DA MENSAGEM DE ERRO POR QUE NÃO CONSEGUE CONVERTER T EM NUMERO)
SELECT 5 + '2' (CONSEGUE CONVERTER 2 EM NUMERO)

2.CASO NÃO EXISTA NENHUM DADO NUMÉRICO 

SELECT 'JOÃO' + ' DA SILVA' (JOÃO DA SILVA)
SELECT '5' + '2' (52)
*/
/*
--PRÁTICA

SELECT VENDA_LIQUIDA + DESCONTO FROM VENDAS_ANALITICAS

SELECT OPERACAO_FISCAL + SITUACAO_TRIBUTARIA FROM VENDAS_ANALITICAS

SELECT ENDERECO
, CIDADE
, ESTADO
, CIDADE + '_' + ESTADO
FROM ENDERECOS
*/

/*
-- 2. FORMA É ULTILIZAR A FUNÇÃO NATIVA CONCAT

SELECT CONCAT (5,2)  (52)
SELECT CONCAT(5,'T') (5T) 
SELECT CONCAT (5,'2') (52) 
SELECT CONCAT('JOÃO',' DA SILVA') (JOÃO DA SILVA)
SELECT CONCAT ('5','2') 


SELECT ENDERECO
, CIDADE
, ESTADO
, CIDADE + '_' + ESTADO AS OPERADOR_MAIS
, CONCAT (CIDADE , '_' , ESTADO) AS OPERADOR_CONCAT
, CONCAT (CIDADE , ESTADO) 
FROM ENDERECOS

*/

------------
--DESAFIO--
------------
/*
SELECT ENTIDADE
, NOME_FANTASIA
, CONCAT (ENTIDADE,'_', NOME_FANTASIA) AS CLIENTES
FROM ENTIDADES

SELECT DESCRICAO
, UNIDADE_MEDIDA
, CONCAT (DESCRICAO,'_',UNIDADE_MEDIDA)
, DESCRICAO + '_' + UNIDADE_MEDIDA AS PRODUTO
FROM PRODUTOS 
*/

/*select produto 
, movimento 
, quantidade
, venda_bruta
from VENDAS_ANALITICAS 
order by produto asc, venda_bruta desc

-- crescente -> ASC
-- decrescente -> DESC
*/
------------
--DESAFIO--
------------
/*
select entidade as C0D_CLIENTE
, INSCRICAO_FEDERAL
, Concat(INSCRICAO_FEDERAL, '_', NOME) as CLIENTE
, DATA_CADASTRO
from ENTIDADES
ORDER BY DATA_CADASTRO DESC
*/
/*
-- OPERADORES DE COMPARAÇÃO 
= IGUAL A 
<> DIFERENTE DE
!= DIFERENTE DE 
> MAIOR QUE 
>= MAIOR OU IGUAL A 
< MENOR QUE 
<= MENOR OU IGUAL A 
*/

/*
SELECT * FROM ENTIDADES
WHERE ENTIDADE <= 1001
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ENTIDADE <> 1
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ENTIDADE < 3100
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ATIVO = 'N'
ORDER BY ENTIDADE 

SELECT * FROM ENTIDADES
WHERE ATIVO <> 'S'
ORDER BY ENTIDADE 
*/

--------------
--DESAFIO 1--
--------------
/*
SELECT 
, CONCAT (ESPECIE_FISCAL,'_', DOCUMENTO_NUMERO) AS DOCUMENTO
, VENDEDOR
, MOVIMENTO
, VENDA_BRUTA
,QUANTIDADE
, PRODUTO
, VENDA_BRUTA / QUANTIDADE  AS VALOR_UNITARIO 
FROM VENDAS_ANALITICAS
WHERE MOVIMENTO > '01/06/2020'
ORDER BY MOVIMENTO ASC
*/
--------------
--DESAFIO 2--
--------------
/*
SELECT 
, VENDEDOR
, MOVIMENTO
, PRODUTO
, QUANTIDADE
, VENDA_BRUTA
, CONCAT (ESPECIE_FISCAL,'_', DOCUMENTO_NUMERO) AS DOCUMENTO
, VENDA_BRUTA / QUANTIDADE  AS VALOR_UNITARIO 
FROM VENDAS_ANALITICAS
WHERE PRODUTO = '34912'
ORDER BY MOVIMENTO DESC
*/
/*
SELECT CIDADE FROM ENDERECOS
WHERE CIDADE = 'SAO PAULO'
*/

--LIKE -> OPERADO DE FILTRO DE CAMPOS VARCHAR (TEXTO)
--(%) -> INDEPENDENTE DO QUE VENHA 
--(_) -> SUBSTITUICAO 
/*
SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'SAO PAULO' -- CORREPONDENCIA EXATA 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE '%LO' -- O QUE TERMINA COM TEXTO INFORMADO(%TEXTO)

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'SA%' -- O QUE COMEÇA COM TEXTO INFOMADO (TEXTO%)

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE '%SA%' -- O QUE CONTÉM COM TEXTO INFOMADO (%TEXTO%)

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'FO_TALEZA' 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE LIKE 'SA_V%' 

SELECT NOME FROM ENTIDADES
WHERE NOME LIKE 'CLIENT__112%'

SELECT NOME FROM ENTIDADES
WHERE NOME LIKE 'CL_ENT__1120'
*/

/*
--NOT LIKE(<>)
--(%) -> INDEPENDENTE DO QUE VENHA 
--(_) -> SUBSTITUICAO 

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE NOT LIKE 'SA%'

SELECT CIDADE FROM ENDERECOS
WHERE CIDADE NOT LIKE '%ES'

*/
/*
-----------------
--DESAFIO 01--
-----------------
SELECT CIDADE
,ESTADO
FROM ENDERECOS
WHERE CIDADE LIKE 'S_O%'
ORDER BY CIDADE DESC

-----------------
--DESAFIO 02--
-----------------
SELECT NOME
,DATA_CADASTRO
FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'
*/

-- AND (E) -> TODAS AS CONDIÇÕES DEVERÃO SER OBEDECIDAS 
-- OR (OU) -> SE PELO MENOS UMA DAS CONDIÇÕES FOREM OBEDECIDAS 
/*
SELECT * FROM ENTIDADES
WHERE ATIVO = 'S'
 AND DATA_CADASTRO >= '18/06/2019'
 AND INSCRICAO_FEDERAL NOT LIKE '%0001%'
 
 SELECT * FROM ENTIDADES
WHERE ATIVO = 'N'
 OR DATA_CADASTRO >= '18/06/2019'
 OR INSCRICAO_FEDERAL NOT LIKE '%0001%'

 SELECT * FROM ENTIDADES
WHERE ENTIDADE = 1001
   OR ENTIDADE = 1002
   OR ENTIDADE = 1003
*/

-- IN  
-- NOT IN 
/*
SELECT * FROM ENTIDADES
WHERE ENTIDADE IN (1001,1,1035,1258,1455,1254)

SELECT CIDADE, ESTADO FROM ENDERECOS
WHERE ESTADO IN ('CE','SP','BA','RJ')
ORDER BY ESTADO 

SELECT * FROM ENTIDADES
WHERE ENTIDADE NOT IN (1001,1,1035,1258,1455,1254)

SELECT CIDADE, ESTADO FROM ENDERECOS
WHERE ESTADO NOT IN ('CE','SP','BA','RJ')
ORDER BY ESTADO 
*/
/*
----------------
--DESAFIO 01--
----------------

SELECT CLIENTE
, QUANTIDADE
, VENDEDOR
, PRODUTO
, MOVIMENTO
FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876, 1422, 2249)
AND QUANTIDADE > 0
AND VENDEDOR IN (4,16)
AND PRODUTO IN( 34726, 34304, 34394, 34593)
ORDER BY MOVIMENTO

--------------
--DESAVIO 02--
--------------

SELECT CLIENTE
, QUANTIDADE
, VENDEDOR
, PRODUTO
, MOVIMENTO
FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876, 1422, 2249)
AND QUANTIDADE > 0
AND VENDEDOR IN (4,16)
AND PRODUTO NOT IN( 34726, 34304, 34394, 34593)
ORDER BY MOVIMENTO
*/ 
/*
-- BETWEEN -> ENTRE 

SELECT * FROM ENTIDADES
WHERE ENTIDADE BETWEEN 1001 AND 1010

SELECT * FROM TITULOS_RECEBER
WHERE VALOR  BETWEEN 0.00 AND 100.00
ORDER BY VALOR 

SELECT * FROM ENTIDADES
WHERE DATA_CADASTRO BETWEEN '01/01/2018' AND '31/01/2018'
ORDER BY DATA_CADASTRO
*/
/*
---------------
--DESAFIO 01--
---------------

SELECT MOVIMENTO
, ENTIDADE
, TITULO
, VALOR
FROM TITULOS_RECEBER
where MOVIMENTO >= '01/01/2020' 
AND ENTIDADE IN (1874, 2308, 1520)
AND TITULO LIKE '%/1%'
AND (VALOR BETWEEN 150.00 AND 255.23
	   OR VALOR BETWEEN 425.57 AND 550.12)
ORDER BY VALOR ASC
*/
/*
select top 100 
* from VENDAS_ANALITICAS

select top 100 
  cliente 
, produto
, quantidade
, venda_bruta
from VENDAS_ANALITICAS

select top 5 percent
  cliente 
, produto
, quantidade
, venda_bruta
, movimento
from VENDAS_ANALITICAS
where movimento >= '01/01/2020'
order by quantidade asc
*/
/*
-- distinct -> ultilizado para deixar valores unicos (não repetidos)
select distinct 
cidade
, estado
from ENDERECOS
where estado = 'sp'
order by cidade 

select distinct 
 cliente
 , produto 
 , venda_liquida + desconto as venda_final 
 from VENDAS_ANALITICAS
 */
----------------------------------------
-------------- MODULO 4 ----------------
----------------------------------------

-- NULL -> TOTALMENTE AUSENTE DE INFORMÇÃO 
-- NULL <> '' (vazio)

/*
select CIDADE, ESTADO, MUNICIPIO, COMPLEMENTO
from enderecos
where MUNICIPIO <> 1832

select CIDADE, ESTADO, MUNICIPIO, COMPLEMENTO
from enderecos
where COMPLEMENTO <> 'cnpj: 00.029.372/0007-36'

SELECT CIDADE, ESTADO, MUNICIPIO, MUNICIPIO +10 
FROM ENDERECOS
*/
---------------------------FUNÇÕES------------------------
-- ISNULL() -> FUNÇÃO PARA TRATAR VALORES NULOS (NULL)
-- COALESCE() -> FUNÇÃO PADÃO ANSI PARA TRATAR VALOR NULOS (NULL)

/*
select CIDADE
, ESTADO
, MUNICIPIO
, COMPLEMENTO
, ISNULL (COMPLEMENTO, 'SEM COMPLEMENTO') AS FUNCAO_ISNULL
, COALESCE (COMPLEMENTO, 'SEM COMPLEMENTO') AS FUNCAO_COALESCE
from enderecos

SELECT COALESCE (VENDEDOR, -1) AS VENDEDOR 
, PRODUTO
, QUANTIDADE 
FROM VENDAS_ANALITICAS

SELECT COALESCE (VENDEDOR, -1) AS VENDEDOR 
, PRODUTO
, QUANTIDADE 
FROM VENDAS_ANALITICAS

select CIDADE
, ESTADO
, MUNICIPIO
, COALESCE (MUNICIPIO, -1)
from enderecos
where COALESCE (MUNICIPIO, -1) = -1 

SELECT CIDADE
, ESTADO
, ISNULL (MUNICIPIO, -1)
FROM ENDERECOS
*/
-----------------------------OPERADORES------------------
/*
IS NULL 
IS NOT NULL 
*/
/*
-----------------------------------------------------------------
-- RECUPERANDO APENAS VALORES NULOS 
SELECT CIDADE
, ESTADO 
, MUNICIPIO
, COALESCE (MUNICIPIO , -1)
FROM ENDERECOS 
WHERE COALESCE(MUNICIPIO , -1)= -1

SELECT CIDADE
, ESTADO 
, MUNICIPIO
, COALESCE (MUNICIPIO , -1)
FROM ENDERECOS 
WHERE MUNICIPIO IS NULL

--------------------------------------------------------------------
-- RECUPERANDO APENAS VALORES NÃO NULOS 
SELECT CIDADE
, ESTADO 
, MUNICIPIO
, COALESCE (MUNICIPIO , -1)
FROM ENDERECOS 
WHERE COALESCE(MUNICIPIO , -1)<> -1

SELECT CIDADE
, ESTADO 
, MUNICIPIO
, COALESCE (MUNICIPIO , -1)
FROM ENDERECOS 
WHERE MUNICIPIO IS NOT NULL
*/
/*
-- NULLIF -> A função NULLIF é usada para retornar NULL se dois valores forem iguais,
--            caso contrário, retorna o primeiro valor.


SELECT CIDADE
, ESTADO 
, COMPLEMENTO
, NULLIF (NULLIF( COMPLEMENTO, '') , 'CNPJ: 00.029.372/0007-36')AS FUNCAO_NULLIF
FROM ENDERECOS

SELECT CIDADE
, ESTADO 
, COMPLEMENTO
, NULLIF (NULLIF( COMPLEMENTO, '') , 'CNPJ: 00.029.372/0007-36')AS FUNCAO_NULLIF
FROM ENDERECOS
WHERE NULLIF (NULLIF (COMPLEMENTO, ''), 'CNPJ: 00.029.372/0007-36') IS  NOT NULL
*/
/*
CEILING() -> ARRENDONDA VALORES PARA BAIXO 
FLOOR() -> ARRENDONDA VALORES PARA CIMA 
ROUND() -> ARRENDONDA VALORES DE ACORDO COM CRITERIOS MATMEMATICOS
ABS() -> RETORNA VALORES ABSOLUTOS 
*/
/*
SELECT TOP 1000
  PRODUTO
, QUANTIDADE
, VENDA_BRUTA
, CEILING(VENDA_BRUTA) AS FUNCAO_CEILING
, FLOOR(VENDA_BRUTA) AS FUNCAO_FLOOR
, ROUND(VENDA_BRUTA,0) AS FUNCAO_ROUND_0
, ROUND(VENDA_BRUTA,1) AS FUNCAO_ROUD_1
, ABS(VENDA_BRUTA) AS FUNCAO_ABS
FROM VENDAS_ANALITICAS

SELECT TOP 1000
  PRODUTO
, QUANTIDADE
, VENDA_BRUTA
, CEILING(VENDA_BRUTA) AS FUNCAO_CEILING
, FLOOR(VENDA_BRUTA) AS FUNCAO_FLOOR
, ROUND(VENDA_BRUTA,0) AS FUNCAO_ROUND_0
, ROUND(VENDA_BRUTA,1) AS FUNCAO_ROUD_1
, ABS(VENDA_BRUTA) AS FUNCAO_ABS
FROM VENDAS_ANALITICAS
WHERE ABS(CEILING(VENDA_BRUTA)) = 360
*/
----------------------------
----------DESAFIO-----------
----------------------------
/*
-- DESAFIO 01

SELECT TOP 100
  COALESCE (VENDEDOR,0) AS VENDEDOR 
, PRODUTO
, QUANTIDADE
, ROUND (VENDA_BRUTA / QUANTIDADE,02)AS VALOR_UNITARIO 
, VENDA_BRUTA 
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NULL 
ORDER BY VALOR_UNITARIO DESC


SELECT TOP 100
  VENDEDOR 
, PRODUTO
, QUANTIDADE
, ROUND (VENDA_BRUTA / QUANTIDADE,02)AS VALOR_UNITARIO 
, VENDA_BRUTA 
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL 
ORDER BY VALOR_UNITARIO DESC
*/