--SELECT*FROM PBS_PROCFIT_ST.dbo.VW_D_EMPRESAS


IF OBJECT_ID('D_EMPRESA')IS NULL
BEGIN 
	CREATE TABLE D_EMPRESA(
	COD_EMPRESA NUMERIC(15) PRIMARY KEY 
  , NOME VARCHAR(160)
  , NOME_FANTASIA VARCHAR(80)
  )
END 