SELECT*FROM PBS_PROCFIT_ST.dbo.VW_D_EMPRESAS
--Criando estrutura para dimensao de empresas

IF OBJECT_ID('D_EMPRESA')IS NULL
BEGIN 
	CREATE TABLE D_EMPRESA(
	COD_EMPRESA	  NUMERIC(15) PRIMARY KEY 
  , NOME		  VARCHAR(160)
  , NOME_FANTASIA VARCHAR(80)
  )
END 

-- Populando dimensão de empresas
--TRUNCATE
TRUNCATE TABLE D_EMPRESA 
INSERT INTO D_EMPRESA

SELECT*FROM PBS_PROCFIT_ST.dbo.VW_D_EMPRESAS

--MERGE
MERGE D_EMPRESA d
USING PBS_PROCFIT_ST.dbo.VW_D_EMPRESAS o ON d.COD_EMPRESA = O.COD_EMPRESA

WHEN MATCHED THEN UPDATE 
SET NOME = o.NOME
,   NOME_FANTASIA = o.NOME_FANTASIA

WHEN NOT MATCHED BY TARGET THEN INSERT (
	COD_EMPRESA	 
  , NOME	
  , NOME_FANTASIA 
)
VALUES (
	COD_EMPRESA	 
  , NOME	
  , NOME_FANTASIA 
);
-- WHEN NOT MATCHED BY SOURGE THEN DELETE; 






