SELECT*FROM PBS_PROCFIT_ST.dbo.VW_D_PRODUTOS

IF OBJECT_ID('D_PRODUTO') IS NULL
BEGIN
	CREATE TABLE D_PRODUTO(
  COD_PRODUTO			NUMERIC (15) PRIMARY KEY
, DESCRICAO				VARCHAR (160)
, DESCRICAO_REDUZIDA 	VARCHAR (80)
, FAMILIA 				VARCHAR (80)
, SECAO 				VARCHAR (80)
, GRUPO 				VARCHAR (80)
, SUB_GRUPO 			VARCHAR (80)
, MARCA 				VARCHAR (80))
END

-- Populando a tabela 

TRUNCATE TABLE D_PRODUTO
INSERT INTO D_PRODUTO
SELECT*FROM PBS_PROCFIT_ST.dbo.VW_D_PRODUTOS
-----------------------------------------------------

MERGE D_PRODUTO d
USING PBS_PROCFIT_ST.dbo.VW_D_PRODUTOS o ON D.COD_PRODUTO = O.COD_PRODUTO

WHEN MATCHED THEN UPDATE
SET   DESCRICAO			 = o.DESCRICAO
	, DESCRICAO_REDUZIDA = o.DESCRICAO_REDUZIDA
	, FAMILIA 			 = o.FAMILIA 
	, SECAO 			 = o.SECAO
	, GRUPO 			 = o.GRUPO
	, SUB_GRUPO 		 = o.SUB_GRUPO 
	, MARCA 			 = o.MARCA 

WHEN NOT MATCHED BY TARGET THEN INSERT (
  DESCRICAO			
, DESCRICAO_REDUZIDA
, FAMILIA 			
, SECAO 			
, GRUPO 			
, SUB_GRUPO 		
, MARCA 	)
VALUES (
  o.DESCRICAO
, o.DESCRICAO_REDUZIDA
, o.FAMILIA 
, o.SECAO
, o.GRUPO
, o.SUB_GRUPO 
, o.MARCA );


