CREATE PROCEDURE USP_FULL_D_VENDEDORES
AS

IF OBJECT_ID('D_VENDEDORES') IS NULL
BEGIN
	CREATE TABLE D_VENDEDORES (
  COD_VENDEDOR NUMERIC(15) PRIMARY KEY  
  , NOME       VARCHAR (180))
END
-- LIMPA TABELA DE DIMENSÃO
TRUNCATE TABLE D_VENDEDORES
-- POPULA DIMENSÃO
INSERT INTO D_VENDEDORES
SELECT*FROM PBS_PROCFIT_ST.dbo.VW_D_VENDEDORES