SP_HELPTEXT USP_DW_CARGA_FULL

CREATE PROCEDURE [dbo].[USP_DW_CARGA_FULL]  
AS  
EXEC USP_FULL_D_CLIENTE  
  
EXEC USP_FULL_D_EMPRESA  
  
EXEC USP_FULL_D_PRODUTO  
  
EXEC USP_FULL_D_VENDEDORES  
  
EXEC USP_CARGA_F_VENDAS 0